### ISSUE TITLE
Missing `exports` section in `package.json`

### ISSUE THREAD

**Issue by susnux** [prantlf/rollup-plugin-esbuild-minify#1]
The `package.json` is missing the `exports` section, so ESM projects with node 16+ will not import it correctly but import the common js entry point.

**Comment by prantlf** [comment]
The `exports` property isn't mandatory. Properties `type`, `main` and `module` support importing from CJS and ESM projects. I myself use this project in both with now Node.js 20.

Nevertheless, I can add the `exports` too.

**Comment by prantlf** [comment]
Fixed in [1.1.2](https://github.com/prantlf/rollup-plugin-esbuild-minify/releases/tag/v1.1.2).

**Comment by susnux** [comment]
Thank you
